name = "gleam_stdlib"
version = "0.67.1"
gleam = ">= 1.13.0"
licences = ["Apache-2.0"]
description = "A standard library for the Gleam programming language"

repository = { type = "github", user = "gleam-lang", repo = "stdlib" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[javascript.deno]
allow_read = ["./"]
